### ISSUE TITLE
TypeError: require(...) is not a function for babel-helper-builder-react-jsx

### ISSUE THREAD

**Issue by lauterry** [theogravity/react-styleguide-generator-alt#30]
Hello

I got the following error when running ./rsg -h

```
 bin git:(documentation) ✗ ./rsg -h
/Users/lauthierry/workspace/front/node_modules/babel-plugin-transform-react-jsx/lib/index.js:12
  var visitor = require("babel-helper-builder-react-jsx")({
                                                         ^

TypeError: require(...) is not a function
    at exports.default (index.js:12:17)
    at Function.memoisePluginContainer (/Users/lauthierry/workspace/front/node_modules/rsg-alt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:109:13)
    at Function.normalisePlugin (/Users/lauthierry/workspace/front/node_modules/rsg-alt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:143:32)
    at /Users/lauthierry/workspace/front/node_modules/rsg-alt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:183:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/lauthierry/workspace/front/node_modules/rsg-alt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:155:20)
    at OptionManager.mergeOptions (/Users/lauthierry/workspace/front/node_modules/rsg-alt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:277:36)
    at /Users/lauthierry/workspace/front/node_modules/rsg-alt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /Users/lauthierry/workspace/front/node_modules/rsg-alt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
    at Array.map (native)
```

I tried for react-styleguide-generator-alt 3.5.0 and 3.5.1 and got the same issue.

I have node 5.9.1

Below is my styleguide.js

```
var path = require('path');

module.exports = {
    "title": "Perfect React Style Guide",
    files: [
        '../build/style.css'
    ]
};
```

Here is my .babelrc

```
{
    "presets": [
        "react",
        "es2015",
        "stage-0"
    ],
    "plugins": [
        "add-module-exports"
    ]
}
```

I cant't see what's wrong

Best regards

**Comment by theogravity** [comment]
I've only tested up to node 4.x. Unsure how `rsg-alt` works with 5. Based on your error, this `babel-helper-builder-react-jsx` is trying to be called as a function when the require doesn't support that.

If you cloned this repo and ran the examples in `examples`, do you still have problems?

```
git clone git@github.com:theogravity/react-styleguide-generator-alt.git
cd react-styleguide-generator-alt/example/
npm install
npm start

#visit http://localhost:3000/
```

**Comment by lauterry** [comment]
Hello

I have to downgrade from node 5.0.0 to 4.3.0.

So the problem disappeared

I close this issue

Best regards
