### ISSUE TITLE
react-docgen/~/doctrine/package.json Module parse failed

### ISSUE THREAD

**Issue by mattdell** [theogravity/react-styleguide-generator-alt#33]
Hello,

I've done the following:
`npm install rsg-alt --save-dev`

Then
`rsg lib/components/inputs/TextInput.js`

And I get this error:
```
{
	"name": "rsg/rsg-lib",
	"hostname": "UK134489.local",
	"pid": 21295,
	"level": 50,
	"msg": "[ './~/react-docgen/~/doctrine/package.json\\nModule parse failed: /Users/mdell/Work/Repos/aztec/web/node_modules/react-docgen/node_modules/doctrine/package.json Unexpected token (2:9)\\nYou may need an appropriate loader to handle this file type.\\nSyntaxError: Unexpected token (2:9)\\n    at Parser.pp.raise (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:920:13)\\n    at Parser.pp.unexpected (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:1483:8)\\n    at Parser.pp.semicolon (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:1462:73)\\n    at Parser.pp.parseExpressionStatement (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:1976:8)\\n    at Parser.pp.parseStatement (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:1754:188)\\n    at Parser.pp.parseBlock (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:1991:21)\\n    at Parser.pp.parseStatement (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:1735:19)\\n    at Parser.pp.parseTopLevel (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:1648:21)\\n    at Parser.parse (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:1616:17)\\n    at Object.parse (/Users/mdell/Work/Repos/aztec/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:882:44)\\n @ ./~/react-docgen/~/doctrine/lib/utility.js 31:14-40' ]",
	"time": "2016-04-28T18:41:50.315Z",
	"v": 0
}
```

Happens on every file.

I'm using Webpack 1.12.2, Babel 5.8.23, and rsg-alt 2.6.3. Any ideas?

**Comment by theogravity** [comment]
Can you try doing `lib/components/inputs/*.js` instead of `TextInput.js`? 

Also have you tried defining a `styleguide.js` or a `styleguide.json`?

```
  # Necessary to use a config file if you want to enable react-docgen
  rsg 'example/**/*.js' -c 'styleguide.json' -v

  # Example 2 - config file does module.exports = { ... }
  rsg 'example/**/*.js' -c 'styleguide.js' -v
```

**Comment by mattdell** [comment]
Thanks for the quick response!

I've just tried the above and it doesn't seem to have resolved the issue.

I grabbed the `styleguide.json` from your example and modified it to reference my generated css file:
```
{
  "title": "React Style Guide",
  "files": [
    "//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css",
    "dist/styles.css"
  ],
  "babelConfig": {
    "stage": 0
  }
}
```

I then added an entry in package.json to run it:
`"rsg": "rsg 'example/**/*.js' -c 'styleguide.json' -v"`

This is the output when I run `npm run rsg`
```
UK134489:web mdell$ npm run rsg

> web-aztec@0.0.1 rsg /Users/mdell/Work/Repos/aztec/web
> rsg 'example/**/*.js' -c 'styleguide.json' -v

{"name":"rsg/rsg-lib","hostname":"UK134489.local","pid":22305,"level":30,"configFile":"/Users/mdell/Work/Repos/aztec/web/styleguide.json","msg":"Reading config file","time":"2016-04-28T19:18:33.992Z","v":0}
{"name":"rsg/rsg-lib","hostname":"UK134489.local","pid":22305,"level":20,"msg":"updating prop docs","time":"2016-04-28T19:18:34.252Z","v":0}
{"name":"rsg/rsg-lib","hostname":"UK134489.local","pid":22305,"level":20,"msg":"writing prop docs","time":"2016-04-28T19:18:34.253Z","v":0}
{"name":"rsg/rsg-lib","hostname":"UK134489.local","pid":22305,"level":50,"msg":"[ './~/react-docgen/~/doctrine/package.json\\nModule parse failed: /Users/mdell/Work/Repos/aztec/web/node_modules/react-docgen/node_modules/doctrine/package.json Unexpected token (2:9)\\nYou may need an appropriate loader to handle this file type.\\nSyntaxError: Unexpected token (2:9)\\n    at Parser.pp.raise (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:920:13)\\n    at Parser.pp.unexpected (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:1483:8)\\n    at Parser.pp.semicolon (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:1462:73)\\n    at Parser.pp.parseExpressionStatement (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:1976:8)\\n    at Parser.pp.parseStatement (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:1754:188)\\n    at Parser.pp.parseBlock (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:1991:21)\\n    at Parser.pp.parseStatement (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:1735:19)\\n    at Parser.pp.parseTopLevel (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:1648:21)\\n    at Parser.parse (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:1616:17)\\n    at Object.parse (/Users/mdell/Work/Repos/aztec/web/node_modules/acorn/dist/acorn.js:882:44)\\n @ ./~/react-docgen/~/doctrine/lib/utility.js 31:14-40' ]","time":"2016-04-28T19:18:38.984Z","v":0}
```

Still seems to fail at the same place unfortunately.

**Comment by theogravity** [comment]
it seems like it's going through the rsg-alt node_modules dir when it shouldn't. I'll check it out this weekend. sorry about that

**Comment by mattdell** [comment]
Thanks in advance for looking into it. Something doesn't seem quite right...

My node / npm versions are
```
$ node -v
v5.1.0
$ npm -v
3.3.12
```

**Comment by mattdell** [comment]
I've done some research and I'm wondering if it has to do with a module requiring `package.json` as the error message seems similar to this: https://github.com/webpack/webpack/issues/303

I have a case in my webpack config to handle json files with json-loader. Does rsg-alt use my webpack file to build or is there another one somewhere?

**Comment by mattdell** [comment]
Yup. I added a loader for json files and that worked!

I'll submit a PR...

**Comment by mattdell** [comment]
Ah, slight problem @theogravity... I've merged the PR for the Babel 6 version and I'm using Babel 5. Can you advise how I can update the 2.6.3 version of rsg-alt?

**Comment by theogravity** [comment]
unpublish the version you published, and roll back your commit to prior your commit then use git push --force to do it

switch to the babel5 branch and just make sure to open a pr against that branch and merge into that (do not merge the babel5 branch to master)

**Comment by mattdell** [comment]
This has now been added to v2.7.0 and v3.5.3 for both Babel 5 / 6 support. Issue can now be closed.

**Comment by theogravity** [comment]
thanks dude!
