### ISSUE TITLE
Components with require('.../image.png') results in an error

### ISSUE THREAD

**Issue by mattdell** [theogravity/react-styleguide-generator-alt#51]
Using require within a react component throws an error when trying to generate the react style guide.

For example, using this bit of code
```
<Image
    src={require('../../../assets/images/PDF-X-icon-64px.png')}
    className='small-doc'
    alt='Remove uploaded document'
    name={upload.name}
    onClick={::this._deleteUpload}/>
```

Results in this error.

```
> web-aztec@3.0.0 rsg /Users/Documents/Aztec/myRepos/web
> rsg lib/components/**/*.styleguide.js -c styleguide.json

{"name":"rsg/rsg-lib","hostname":"UK160570.local","pid":11649,"level":50,"msg":"[ './assets/images/PDF-X-icon-64px.png\\nModule parse failed: /Users/Documents/Aztec/myRepos/web/assets/images/PDF-X-icon-64px.png Unexpected character \\'�\\' (1:0)\\nYou may need an appropriate loader to handle this file type.\\nSyntaxError: Unexpected character \\'�\\' (1:0)\\n    at Parser.pp.raise (/Users/Documents/Aztec/myRepos/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:920:13)\\n    at Parser.pp.getTokenFromCode (/Users/Documents/Aztec/myRepos/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:2813:8)\\n    at Parser.pp.readToken (/Users/Documents/Aztec/myRepos/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:2508:15)\\n    at Parser.pp.nextToken (/Users/Documents/Aztec/myRepos/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:2500:71)\\n    at Parser.parse (/Users/Documents/Aztec/myRepos/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:1615:10)\\n    at Object.parse (/Users/Documents/Aztec/myRepos/web/node_modules/webpack/node_modules/acorn/dist/acorn.js:882:44)\\n    at Parser.parse (/Users/Documents/Aztec/myRepos/web/node_modules/webpack/lib/Parser.js:902:15)\\n    at DependenciesBlock.<anonymous> (/Users/Documents/Aztec/myRepos/web/node_modules/webpack/lib/NormalModule.js:104:16)\\n    at DependenciesBlock.onModuleBuild (/Users/Documents/Aztec/myRepos/web/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)\\n    at nextLoader (/Users/Documents/Aztec/myRepos/web/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)\\n @ ./lib/components/common/UploadsList.js 150:13-66' ]","time":"2016-06-16T14:09:48.646Z","v":0}

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "rsg"
npm ERR! node v5.0.0
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE
npm ERR! web-aztec@3.0.0 rsg: `rsg lib/components/**/*.styleguide.js -c styleguide.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-aztec@3.0.0 rsg script 'rsg lib/components/**/*.styleguide.js -c styleguide.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web-aztec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rsg lib/components/**/*.styleguide.js -c styleguide.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web-aztec
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web-aztec
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Documents/Aztec/myRepos/web/npm-debug.log
```

The answer to this is that we don't have a webpack loader for images. I would suggest implementing url-loader: https://github.com/webpack/url-loader

**Comment by mattdell** [comment]
The approach suggested is to pass your own webpack config file as a config option to RSG.
