### ISSUE TITLE
Cannot find module 'react/addons'

### ISSUE THREAD

**Issue by kbrah** [theogravity/react-styleguide-generator-alt#65]
When I try to build the documentation it throws this error. What to do?

`rsg 'src/components/_components_/**/*.jsx' -o documents -v`
```
{"name":"rsg/rsg-lib","hostname":"DESKTOP-Q3H080G","pid":8244,"level":50,"err":{"message":"Cannot find module 'react/addons' from 'C:\\Users\\Lasse\\Projects\\Project 2.0'","name":"Error","stack":"Error: Cannot find module 'react/addons' from 'C:\\Users\\Lasse\\Projects\\Project 2.0'\n    at C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:46:17\n    at process (C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:173:43)\n    at ondir (C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:188:17)\n    at load (C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:69:43)\n    at onex (C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:92:31)\n    at C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:22:47\n    at FSReqWrap.oncomplete (fs.js:82:15)"},"msg":"Cannot find module 'react/addons' from 'C:\\Users\\Lasse\\Projects\\Project 2.0'","time":"2016-07-27T09:20:02.783Z","v":0}
{"name":"rsg/bin","hostname":"DESKTOP-Q3H080G","pid":8244,"level":50,"err":{"message":"Cannot find module 'react/addons' from 'C:\\Users\\Lasse\\Projects\\Project 2.0'","name":"Error","stack":"Error: Cannot find module 'react/addons' from 'C:\\Users\\Lasse\\Projects\\Project 2.0'\n    at C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:46:17\n    at process (C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:173:43)\n    at ondir (C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:188:17)\n    at load (C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:69:43)\n    at onex (C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:92:31)\n    at C:\\Users\\Lasse\\AppData\\Roaming\\npm\\node_modules\\react-styleguide-generator\\node_modules\\browserify\\node_modules\\resolve\\lib\\async.js:22:47\n    at FSReqWrap.oncomplete (fs.js:82:15)"},"msg":"Cannot find module 'react/addons' from 'C:\\Users\\Lasse\\Projects\\Project 2.0'","time":"2016-07-27T09:20:02.881Z","v":0}
```

**Comment by kbrah** [comment]
Installing rsg-alt globally fixed this error but now it's giving me this.
Perhaps this is related to #24 ?

```
{
  "name": "rsg/rsg-lib",
  "hostname": "DESKTOP-Q3H080G",
  "pid": 7364,
  "level": 50,
  "msg": "[
 'C:/Users/Lasse/AppData/Roaming/npm/~/rsg-alt/app/index.js\\nModule parse failed: C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\app\\\\index.js Unexpected token (14:18)\\nYou may need an appropriate loader to handle this file type.\\nSyntaxError: Unexpected token (14:18)\\n    at Parser.pp$4.raise (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:2221:15)\\n    at Parser.pp.unexpected (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:603:10)\\n    at Parser.pp$3.parseExprAtom (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1822:12)\\n    at Parser.pp$3.parseExprSubscripts (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1715:21)\\n    at Parser.pp$3.parseMaybeUnary (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1692:19)\\n    at Parser.pp$3.parseExprOps (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1637:21)\\n    at Parser.pp$3.parseMaybeConditional (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1620:21)\\n    at Parser.pp$3.parseMaybeAssign (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1597:21)\\n    at Parser.pp$3.parseExprList (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:2165:22)\\n    at Parser.pp$3.parseSubscripts (C:\\\\Users\\\\Lasse\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1741:35)\\n @ multi app'
 ]",
  "time": "2016-07-27T11:08:27.605Z",
  "v": 0
}
```

**Comment by bendman** [comment]
@kbrah installing `rsg-alt` globally won't work, as you could tell by your second comment, which is directly related to having it installed globally.

I'm not sure why you are having an issue with react-addons though...

**Comment by theogravity** [comment]
What version of node / npm are you using? Are you running `npm i` and `npm run start` in the `example` directory?

**Comment by kbrah** [comment]
@theogravity 
node v4.4.5
npm v2.15.5

I now tried to do the example and got this error. I did npm install and npm run start. I also removed the global installation of rsg alt with `npm rm -g rsg-alt`. Also for some reason it won't recognize rsg command on cmd when I'm at example directory (is it supposed to?)
```
> npm run styleguide && npm run serve


> rsg-alt-example@ styleguide C:\Users\Lasse\Projects\react-styleguide-generator-alt\example
> rsg "components/**/*.js"


{
  "name": "rsg/rsg-lib",
  "hostname": "DESKTOP-Q3H080G",
  "pid": 3672,
  "level": 50,
  "msg": "[ './~/rsg-alt/app/index.js\\n
      Module parse failed: C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-   alt\\\\example\\\\node_modules\\\\rsg-alt\\\\app\\\\index.js Unexpected token (14:18)\\n
      You may need an appropriate loader to handle this file type.\\n
      SyntaxError: Unexpected token (14:18)\\n
         at Parser.pp$4.raise (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-   alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:2221:15)\\n
         at Parser.pp.unexpected (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:603:10)\\n
         at Parser.pp$3.parseExprAtom (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1822:12)\\n
         at Parser.pp$3.parseExprSubscripts (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1715:21)\\n
         at Parser.pp$3.parseMaybeUnary (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1692:19)\\n
         at Parser.pp$3.parseExprOps (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1637:21)\\n
         at Parser.pp$3.parseMaybeConditional (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1620:21)\\n
         at Parser.pp$3.parseMaybeAssign (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1597:21)\\n
         at Parser.pp$3.parseExprList (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:2165:22)\\n
         at Parser.pp$3.parseSubscripts (C:\\\\Users\\\\Lasse\\\\Projects\\\\react-styleguide-generator-alt\\\\example\\\\node_modules\\\\rsg-alt\\\\node_modules\\\\webpack\\\\node_modules\\\\acorn\\\\dist\\\\acorn.js:1741:35)\\n
 @ multi app' ]",
  "time": "2016-07-28T06:01:39.546Z",
  "v": 0
}

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "styleguide"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! rsg-alt-example@ styleguide: `rsg "components/**/*.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rsg-alt-example@ styleguide script 'rsg "components/**/*.js"'.
npm ERR! This is most likely a problem with the rsg-alt-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rsg "components/**/*.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rsg-alt-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls rsg-alt-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Lasse\Projects\react-styleguide-generator-alt\example\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! rsg-alt-example@ start: `npm run styleguide && npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rsg-alt-example@ start script 'npm run styleguide && npm run serve'.
npm ERR! This is most likely a problem with the rsg-alt-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run styleguide && npm run serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rsg-alt-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls rsg-alt-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Lasse\Projects\react-styleguide-generator-alt\example\npm-debug.log
```

**Comment by theogravity** [comment]
Hrm, thought node / npm ver might be an issue but I'm not seeing the problem on the same ver on OS X:

```bash
[theo@theo-viv-mac react-styleguide-generator-alt (master)]$ nvm i v4.4.5
######################################################################## 100.0%
Checksums empty
Now using node v4.4.5 (npm v2.15.5)
[theo@theo-viv-mac react-styleguide-generator-alt (master)]$ cd example/
[theo@theo-viv-mac example (master)]$ npm i
....
[theo@theo-viv-mac example (master)]$ npm run start

> rsg-alt-example@ start /Volumes/sixfive-cs/react-styleguide-generator-alt/example
> npm run styleguide && npm run serve


> rsg-alt-example@ styleguide /Volumes/sixfive-cs/react-styleguide-generator-alt/example
> rsg "components/**/*.js"


> rsg-alt-example@ serve /Volumes/sixfive-cs/react-styleguide-generator-alt/example
> serve ./styleguide

serving /Volumes/sixfive-cs/react-styleguide-generator-alt/example/styleguide on port 3000
GET / 200 10ms - 922
GET /src/vendor.bundle.js 200 7ms - 23.68kb
GET /files/example.css 200 14ms - 189
GET /src/bundle.js 200 68ms - 1.89mb
```

**Comment by theogravity** [comment]
So, I'm able to get an error when I run `npm run styleguide` vs `npm run start`

There shouldn't be any core differences... unsure what's going on there.

Try `npm run start` ?

**Comment by theogravity** [comment]
Unsure if it's an issue limited to node windows at the moment...

**Comment by kbrah** [comment]
I did try npm run start with no success

**Comment by theogravity** [comment]
Sorry - when I made my now deleted comment, it was because I switched my node version back to 6, which resulted in errors.

**Comment by kbrah** [comment]
#24 proposed fix seemed to fix my problem too. I tried it earlier but I guess I was doing something wrong  at that time. However in my own project it still does not work. It cannot resolve a utils.js file that I use in my component. Is this because I need to inject the reference in files:[]? I tried that without success

**Comment by kbrah** [comment]
It tries to resolve the file from node_modules directory

**Comment by theogravity** [comment]
Two possibilities:

- See bottom of https://github.com/theogravity/react-styleguide-generator-alt/issues/61 if your project is affected
- overriding `resolve` / `resolveLoader` might help in some way

https://github.com/theogravity/react-styleguide-generator-alt/blob/master/lib/rsg.js#L338

**Comment by kbrah** [comment]
I tried the suggested fix in #64 but it did not affect the error. Do you mean overriding by changing the code or through some config? sorry I'm a bit of a noob at these things :/

**Comment by theogravity** [comment]
np, overriding by changing your webpack config (if you're attempting to integrate your project with it).

if you're just having issues running the examples, then #64 wouldn't apply

**Comment by kbrah** [comment]
example is now fine

**Comment by kbrah** [comment]
I did this and now it works!! Thanks a lot for the help! :)
```
resolve: {
      fallback: path.resolve('./src/')
    },
```
