### ISSUE TITLE
Loading individual css into components issue

### ISSUE THREAD

**Issue by jcleefw** [theogravity/react-styleguide-generator-alt#75]
Hi There,

I want to be able to include individual stylesheets into a single component. 

```
import React, { Component } from 'react';
import './Button.css';
```

However I'm getting error in rsg. in .`/example/components/Buttons/Button.css. Module parse failed: /private/tmp/react-styleguide-generator-alt/example/components/Buttons/Button.css Unexpected token (1:11) You may need an appropriate loader to handle this file type.`

Can you please advise what can i do

**Comment by theogravity** [comment]
You need to add the webpack loaders specific for loading css and add that to the webpack config.

Something like:

```
// styleguide.js
module.exports = {
  ...
  webpackConfig": {
    loaders: [
      
    ]
  }
}
```

**Comment by arsdehnel** [comment]
Having the same problem here and trying to add the webpackConfig doesn't seem to be changing anything.  Trying with just a simple component:

```jsx
import React from 'react';
import LocaleString from '../../components-shared/locale-string/locale-string.jsx';

import './progress-header-message.scss';

class ProgramHeaderMessage extends React.Component {

	static styleguide = {
		index: '1.1',
		category: 'Elements',
		title: 'Button',
		description: 'You can use **Markdown** within this `description` field.',
		code: `<Button size='small|large' onClick=${Function}>Cool Button</Button>`,
		className: 'apply the css class'
	}

    render() {

        return (
            <div className="progress-header-message">
				<h2>
					<LocaleString code="progress.oops"/>
				</h2>
				<h3>
					<LocaleString code="progress.noSelection"/>
				</h3>
				<p>
					<LocaleString code="progress.noSelectionSubText"/>
				</p>
            </div>
        );
    }

}
export default ProgramHeaderMessage;
```

and my styleguide.js looks like this:

```javascript
// styleguide.js
// styleguide.js
module.exports = {
	title: 'React Style Guide',
	webpackConfig: {
		loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                query: {compact: false},
                exclude: /(node_modules)/
            },
            {
                test: /\.scss$/,
                loader: 'style!css!postcss-loader!sass'
            }
        ]
	}
};
```

and then i run it in verbose mode and get this:

```
{"name":"rsg/rsg-lib","hostname":"dehnel-15mb","pid":30952,"level":30,"configFile":"/Users/dehnel/Projects/goalquest/pax-site/styleguide.js","msg":"Reading config file","time":"2016-12-10T20:52:03.330Z","v":0}
{"name":"rsg/rsg-lib","hostname":"dehnel-15mb","pid":30952,"level":20,"file":"/Users/dehnel/Projects/goalquest/pax-site/src/app/components-shared/progress-header-message/progress-header-message.jsx","msg":"styleguide input file","time":"2016-12-10T20:52:03.528Z","v":0}
{"name":"rsg/rsg-lib","hostname":"dehnel-15mb","pid":30952,"level":20,"msg":"updating prop docs","time":"2016-12-10T20:52:03.585Z","v":0}
{"name":"rsg/rsg-lib","hostname":"dehnel-15mb","pid":30952,"level":20,"msg":"writing prop docs","time":"2016-12-10T20:52:03.616Z","v":0}
{"name":"rsg/rsg-lib","hostname":"dehnel-15mb","pid":30952,"level":50,"msg":"[ './src/app/components-shared/progress-header-message/progress-header-message.scss\\nModule parse failed: /Users/dehnel/Projects/goalquest/pax-site/src/app/components-shared/progress-header-message/progress-header-message.scss Unexpected token (1:0)\\nYou may need an appropriate loader to handle this file type.\\nSyntaxError: Unexpected token (1:0)\\n    at Parser.pp$4.raise (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:2221:15)\\n    at Parser.pp.unexpected (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:603:10)\\n    at Parser.pp$3.parseExprAtom (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:1822:12)\\n    at Parser.pp$3.parseExprSubscripts (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:1715:21)\\n    at Parser.pp$3.parseMaybeUnary (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:1692:19)\\n    at Parser.pp$3.parseExprOps (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:1637:21)\\n    at Parser.pp$3.parseMaybeConditional (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:1620:21)\\n    at Parser.pp$3.parseMaybeAssign (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:1597:21)\\n    at Parser.pp$3.parseExpression (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:1573:21)\\n    at Parser.pp$1.parseStatement (/Users/dehnel/Projects/goalquest/pax-site/node_modules/acorn/dist/acorn.js:727:47)\\n @ ./src/app/components-shared/progress-header-message/progress-header-message.jsx 17:0-41' ]","time":"2016-12-10T20:52:06.772Z","v":0}
```

Not sure where to go from here, any help would be awesome!

**Comment by theogravity** [comment]
I'd you try using include: [<path to your scss file>] in the loader config for scss does it work

**Comment by arsdehnel** [comment]
Assuming you mean this:

```
module.exports = {
	title: 'React Style Guide',
	webpackConfig: {
		loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                query: {compact: false},
                exclude: /(node_modules)/
            },
            {
                test: /\.scss$/,
                loader: 'style!css!postcss-loader!sass',
                include: []
            }
        ]
	}
};
```

that doesn't work either.  Even if I remove the `-c styleguide.js` from the command it does the same thing.  Like it's not reading my config file or something.

**Comment by stephs829** [comment]
Just fixed this same issue for anyone else that faces it - module key is missing from the example above. Here's my `styleguide.js` which worked by including it in package.json script like so `rsg 'src/js/components/**/*.js' -d -c 'styleguide.js' -v`:

```
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
	title: 'React Style Guide',
	webpackConfig: {
    module: {
      loaders: [
        {
          test: /\.scss$/,
          exclude: /node_modules/,
          loader: ExtractTextPlugin.extract('style', 'css!sass')
        }
      ],
    }
	}
}
```
