### ISSUE TITLE
Babel 6.4 semicolon problem

### ISSUE THREAD

**Issue by gabrielpugliese-luizalabs** [theogravity/react-styleguide-generator-alt#9]
Hi,

Thanks for the help. The trace is (is there any way to beautfify this?):
```
> node_modules/rsg-alt/bin/rsg containers/App.js

{"name":"rsg/rsg-lib","hostname":"sapobook","pid":93843,"level":50,"msg":"[ './~/rsg-alt/app/components/App/index.js\\nModule build failed: SyntaxError: /Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/rsg-alt/app/components/App/index.js: A semicolo
n is required after a class property (7:31)\\n\\u001b[0m   5 | \\n   6 | \\u001b[36mexport\\u001b[39m \\u001b[36mdefault\\u001b[39m \\u001b[36mclass\\u001b[39m App \\u001b[36mextends\\u001b[39m Component \\u001b[32m{\\u001b[39m\\n>  7 |   static displayName \\u001b[1m=\
\u001b[22m \\u001b[31m\\'SG.App\\'\\u001b[39m\\n     |                                ^\\n   8 | \\n   9 |   static propTypes \\u001b[1m=\\u001b[22m \\u001b[32m{\\u001b[39m\\n  10 |     ctx\\u001b[1m:\\u001b[22m PropTypes\\u001b[1m.\\u001b[22mobject\\u001b[1m.\\u001b[22
misRequired\\u001b[0m\\n    at Parser.pp.raise (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:1413:13)\\n    at Parser.pp.parseClassProperty (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:
2565:10)\\n    at Parser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)\\n    at Parser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)\\n    at Pa
rser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)\\n    at Parser.parseClassProperty (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)\\n    at Parser.pp.parse
ClassBody (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:2470:34)\\n    at Parser.pp.parseClass (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:2413:8)\\n    at Parser.pp.parseExport (/User
s/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:2630:19)\\n    at Parser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3625:20)\\n @ ./~/rsg-alt/app/index.js 15:11-38' ]","time":"201
6-01-08T19:46:41.470Z","v":0}
```

My package.json is:

```
{
  "name": "react-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "NODE_ENV=test mocha --recursive --compilers js:babel-register --require ./test/setup.js test/**/*.spec.js",
    "test:cov": "NODE_ENV=test babel-node node_modules/isparta/bin/isparta cover --report text --report html node_modules/mocha/bin/_mocha -- --recursive --compilers js:babel-register --require ./test/setup.js test/**/*.spec.js",
    "test:watch": "npm test -- --watch",
    "start": "webpack-dev-server",
    "check": "npm-check -s",
    "check:u": "npm-check -u",
    "lint": "eslint .",
    "lint:fix": "eslint --fix .",
    "build": "ENV=production webpack --config webpack.prod.config.js",
    "styleguide": "node_modules/rsg-alt/bin/rsg containers/App.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-cli": "~6.3.17",
    "babel-core": "~6.3.26",
    "babel-eslint": "^4.1.6",
    "babel-loader": "^6.2.1",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-plugin-react-transform": "^2.0.0-beta1",
    "babel-plugin-rewire": "^1.0.0-beta-3",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "~6.3.0",
    "babel-polyfill": "^6.3.14",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-register": "^6.3.13",
    "babel-runtime": "^6.3.19",
    "css-loader": "^0.23.1",
    "es3ify-loader": "^0.1.0",
    "eslint": "^1.10.3",
    "eslint-config-airbnb": "^2.1.1",
    "eslint-plugin-mocha": "^1.1.0",
    "eslint-plugin-react": "^3.14.0",
    "expect": "^1.13.4",
    "isparta": "^4.0.0",
    "jsdom": "^7.2.2",
    "mocha": "^2.3.4",
    "node-bourbon": "^4.2.3",
    "node-sass": "^3.4.2",
    "npm-check": "^4.1.3",
    "react-styleguide-generator": "^1.2.1",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.2.0",
    "rewire": "^2.5.1",
    "rsg-alt": "^3.1.0",
    "sass-loader": "^3.1.2",
    "style-loader": "^0.13.0",
    "webpack": "^1.12.10",
    "webpack-dev-middleware": "^1.4.0",
    "webpack-dev-server": "^1.14.0",
    "webpack-hot-middleware": "^2.6.0"
  },
  "dependencies": {
    "history": "^1.17.0",
    "lokka": "^1.6.1",
    "lokka-transport-http": "^1.3.0",
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "react-redux": "^4.0.6",
    "react-router": "^1.0.3",
    "redux": "^3.0.5",
    "redux-form": "^4.1.1",
    "redux-logger": "^2.3.1",
    "redux-simple-router": "^1.0.2",
    "redux-thunk": "^1.0.3"
  }
}
```

This is my App.js:
```
const React = require('react');
const { Component } = React;

const FormContainer = require('./FormContainer');
const ProductLinkContainer = require('./ProductLinkContainer');

module.exports = class App extends Component {
  static styleguide = {
    index: '1.1',
    category: 'components',
    title: 'App',
    description: 'Some **App**',
    code: '<App />',
    className: 'css class'
  };

  render() {
    return (
      <div>
        <FormContainer />
        <ProductLinkContainer />
      </div>
    );
  }
};
```

`npm ls | grep babel | grep 6.4`:
```
│ ├─┬ babel-generator@6.4.2
│ ├─┬ babel-helpers@6.4.0
│ ├─┬ babel-types@6.4.1
│ ├─┬ babelify@6.4.0
```

**Comment by gabrielpugliese-luizalabs** [comment]
Forgot the `.babelrc`:
```
{
    "presets": ["es2015", "stage-0", "react"],
    "plugins": [
        ["transform-decorators-legacy"]
    ],
    "env": {
        "test": {
            "plugins": [
                ["rewire", {
                    "transforms": [{
                        "transform": "add-module-exports"
                    }]
                }]
            ]
        },
        "production": {
            "plugins": [
                ["babel-plugin-transform-es2015-modules-commonjs"],
                ["babel-plugin-transform-es3-member-expression-literals"],
                ["babel-plugin-transform-es3-property-literals"]
            ]
        }
    }
}
```

**Comment by theogravity** [comment]
What if you tried fixing the 6.4 babel items to 6.3?

I'm having probs parsing the JSON error. I'll have to fix that (probably in around a day).

**Comment by gabrielpugliese-luizalabs** [comment]
I've parsed it:
```
"[ './~/rsg-alt/app/components/App/index.js
Module build failed: SyntaxError: /Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/rsg-alt/app/components/App/index.js: A semicolon is required after a class property (7:31)
   5 |
   6 | export default class App extends Component {
>  7 |   static displayName = 'SG.App'
     |                                ^
   8 |
   9 |   static propTypes = {
  10 |     ctx: PropTypes.object.isRequired
    at Parser.pp.raise (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:1413:13)
    at Parser.pp.parseClassProperty (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:2565:10)
    at Parser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)
    at Parser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)
    at Parser.<anonymous> (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)
    at Parser.parseClassProperty (/Users/gabrielpugliese/Test/maga-graphql-redux/react-app/node_modules/babylon/index.js:3774:20)
```

**Comment by theogravity** [comment]
Yeah I was able to see it despite the parsing issues. 

```
│ ├─┬ babel-generator@6.4.2
│ ├─┬ babel-helpers@6.4.0
│ ├─┬ babel-types@6.4.1
│ ├─┬ babelify@6.4.
```

Can you try doing an npm install --save on those items?

**Comment by gabrielpugliese-luizalabs** [comment]
Did it but version didn't change. Gonna try to force ~6.3.0

**Comment by gabrielpugliese-luizalabs** [comment]
Man...so many dependencies with babel@6.4 installed probably because package.json "^6.3.x".

**Comment by gabrielpugliese-luizalabs** [comment]
How come those dependencies can affect rsg-alt? Because it is depending from babel-core@6.3.26

**Comment by theogravity** [comment]
Unsure, actually. My procedure was as I've told you - look at what other babel deps were installed from my base deps and see what versions were being installed and try to save a downgraded version to my package json :(

The ^ will definitely pick up minor versions, whereas the ~ will do patch level.

**Comment by theogravity** [comment]
https://github.com/feross/standard/issues/372 also recommend using `--save-exact` as well to get a fixed version

**Comment by theogravity** [comment]
also make sure you clear out your `node_modules` dir before reinstalling

**Comment by gabrielpugliese-luizalabs** [comment]
Yeah tried all those. That's so frustrating. I will keep you updated.

**Comment by CookPete** [comment]
Just chipping in. It looks like the "fix" happened in `v6.4.0` of the `babylon` package (https://github.com/babel/babel/pull/3225), which is the JS parser used by `babel`. Pinning `babel-core`, `babel-cli` etc to `6.3.x` is not enough, because they in turn require `babylon@^6.3.x` which will now install `babylon@6.4.x` which requires the semicolons.

What I've done for the time being is use a partial `shrinkwrap` to pin `babel-core`, `babel-cli` and `babylon` to `6.3.x`, which temporarily solves the issue: https://github.com/CookPete/react-player/commit/630072c5554c2a01cdd1bf69c40b1bec3da8e480. It's not ideal but it prevents the build error for now.

**Comment by theogravity** [comment]
Thanks, @CookPete! It's definitely frustrating to track down package subdeps to see which versions are getting installed. Looking at the rsg package.json last changes, I introduced `"babylon": "~6.3.26"`, which probably helped fixed my issues (along with downgrading other packages)

**Comment by theogravity** [comment]
Also if both of you have package fixes that you feel rsg should have, feel free to submit a PR - I'll be happy give push / merge / npm publish rights

**Comment by gabrielpugliese-luizalabs** [comment]
Thanks @CookPete, didn't know about npm-shrinkwrap :+1: 
The error is now gone, but since I'm using decorators it changed to: `Decorators are not supported yet in 6.x pending proposal update.` which does not make sense because I have .babelrc with `transform-decorators-legacy` plugin and works in webpack. Although replacing decorators with simple function calls makes the build finish. Any idea on this? Tried creating a styleguide.json and passing as `-c` arg didn't work either:
```
{
  "title": "Stylguide",
  "babelConfig": {
    "presets": ["es2015", "stage-0", "react"],
    "plugins": [
      ["transform-decorators-legacy"]
    ]
  }
}
```

**Comment by theogravity** [comment]
@gabrielhpugliese Could be that you also have to modify webpack as well? I use `babel-loader` here:

https://github.com/theogravity/react-styleguide-generator-alt/blob/master/lib/rsg.js#L265

It could be that we'll have to add in an override for custom options to use

**Comment by gabrielhpugliese** [comment]
Hey no problem!

I has to move with the project so I've downgraded to 6.3.x :/
When I upgrade to 6.4 someday I report here :)

**Comment by theogravity** [comment]
There was a release just around 9 hours ago with the semicolon fix - https://github.com/babel/babel/releases/tag/v6.5.2

@gregz67 would you be interested in updating your former PR to use 6.5.2?
